"""Add duracao to appointment

Revision ID: 063c4dd8b818
Revises: 2c50ffec103f
Create Date: 2025-08-13 02:26:03.980808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063c4dd8b818'
down_revision = '2c50ffec103f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duracao', sa.Integer(), nullable=False, server_default='30'))
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))

    # ### end Alembic commands ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('duracao', server_default=None)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('observacoes')
        batch_op.drop_column('duracao')

    # ### end Alembic commands ###
