"""Migracao inicial com todas as tabelas

Revision ID: ee0e10d0afdc
Revises: 
Create Date: 2025-08-12 23:32:29.000032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee0e10d0afdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('nome_social', sa.String(length=150), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('paciente_dependente', sa.String(length=10), nullable=True),
    sa.Column('nome_dependente', sa.String(length=150), nullable=True),
    sa.Column('data_nascimento_dependente', sa.Date(), nullable=True),
    sa.Column('idade_dependente', sa.Integer(), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('escolaridade', sa.String(length=50), nullable=False),
    sa.Column('religiao', sa.String(length=100), nullable=True),
    sa.Column('estado_civil', sa.String(length=50), nullable=False),
    sa.Column('servico_buscado', sa.String(length=50), nullable=False),
    sa.Column('servico_buscado_outro', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('nome_completo', sa.String(length=120), nullable=False),
    sa.Column('funcao', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('sala', sa.String(length=20), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('data_sessao', sa.DateTime(), nullable=False),
    sa.Column('evolucao', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_record')
    op.drop_table('appointment')
    op.drop_table('user')
    op.drop_table('patient')
    # ### end Alembic commands ###
